---
clickhouse_version: "22.3.3.44"
clickhouse_packages:  
  - clickhouse-client   
  - clickhouse-server
  - clickhouse-common-static
# all_clickhouse_table: "logs_table"
# all_clickhouse_db: "logs"
# all_clickhouse_url: "http://locakhost:8123"  
  
  